//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GeneralInsuranceEntities : DbContext
    {
        public GeneralInsuranceEntities()
            : base("name=GeneralInsuranceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClaimInfo> ClaimInfoes { get; set; }
        public virtual DbSet<InsurancePlanInfo> InsurancePlanInfoes { get; set; }
        public virtual DbSet<PolicyInfoTB> PolicyInfoTBs { get; set; }
        public virtual DbSet<RegistrationInfo> RegistrationInfoes { get; set; }
        public virtual DbSet<VehicleInsuranceInfo> VehicleInsuranceInfoes { get; set; }
    }
}
