//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegistrationInfo()
        {
            this.InsurancePlanInfoes = new HashSet<InsurancePlanInfo>();
            this.VehicleInsuranceInfoes = new HashSet<VehicleInsuranceInfo>();
        }
    
        public int Reg_Id { get; set; }
        public string Reg_Name { get; set; }
        public string Reg_Email { get; set; }
        public Nullable<System.DateTime> Reg_DOB { get; set; }
        public Nullable<float> Reg_Phone { get; set; }
        public string Reg_Address { get; set; }
        public string Reg_Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsurancePlanInfo> InsurancePlanInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleInsuranceInfo> VehicleInsuranceInfoes { get; set; }
    }
}
