//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleInsuranceInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleInsuranceInfo()
        {
            this.InsurancePlanInfoes = new HashSet<InsurancePlanInfo>();
            this.PolicyInfoTBs = new HashSet<PolicyInfoTB>();
        }
    
        public int Vehicle_ID { get; set; }
        public string Vehicle_Type { get; set; }
        public string Vehicle_Manufacturer { get; set; }
        public string Vehicle_Model { get; set; }
        public string Driving_Licence { get; set; }
        public Nullable<System.DateTime> Vehicle_DOP { get; set; }
        public string Vehicle_Regis_No { get; set; }
        public string Vehicle_Engine_No { get; set; }
        public string Vehicle_Chassis_No { get; set; }
        public Nullable<int> Registration_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsurancePlanInfo> InsurancePlanInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolicyInfoTB> PolicyInfoTBs { get; set; }
        public virtual RegistrationInfo RegistrationInfo { get; set; }
    }
}
